dataset: 'mmBody'
t_his: 8
t_pred: 16
batch_size: 128
num_epoch: 500
num_data_sample: 50000
num_val_data_sample: 5000
lr: 3.e-4
n_pre: 10
n_pre_cond: 10
multimodal_path: ./data/data_multi_modal/t_his25_1_thre0.500_t_pred100_thre0.100_filtered_dlow.npz
data_candi_path: ./data/data_multi_modal/data_candi_t_his25_t_pred100_skiprate20.npz
padding: 'LastFrame'
Complete: True
noise_steps: 1000
ddim_timesteps: 100
refine_timesteps: 0
scheduler: 'Cosine' # 'Cosine' 'Linear' 'Sqrt' 'Sigmoid'
num_layers: 8
num_T_in_M_layers: 1
num_T_in_M_head: 4
num_heads: 8
latent_dims: 512
dropout: 0.2
mod_train: 0.8
mod_test: 1.0
dct_norm_enable: False

dct_i: 4 

dct_enable: True # whether use DCT domain
dct_dev1_enable: False # whether use DCT domain
inner_dct_enable: False # not applicable
vel_enable: False # whether use velocity domain


diff_err_loss: True # whether use loss training and inference
diff_err_mask: False # whether use mask training